spring:
  application:
    name: home-mind
  ai:
#    openai:
#      base-url: https://api.siliconflow.cn
#      api-key: sk-amjufwzxcubqozmgtnimekrfsshtruprvjkvbuxcwtrzzcgt
#      chat:
#        options:
#          model: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
#          temperature: 0.7
    deepseek:
      api-key: sk-31ce56b6e1a94f73a4e40585b489ffef
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:9000
        toolcallback:
          enabled: true

baidu:
  speech:
    api-key: NK3SFZjNgyggjUjJqvwukONC
    secret-key: kIfuAekCj2PntwoiOTBTCtZvqfGnYaVT

