spring:
  application:
    name: home-mind
  ai:
#    openai:
#      base-url: https://api.siliconflow.cn
#      api-key: sk-amjufwzxcubqozmgtnimekrfsshtruprvjkvbuxcwtrzzcgt
#      chat:
#        options:
#          model: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
#          temperature: 0.7
    deepseek:
      api-key: xxx

home-assistant:
  url: xxx
  token: xxx

baidu:
  speech:
    api-key: NK3SFZjNgyggjUjJqvwukONC
    secret-key: kIfuAekCj2PntwoiOTBTCtZvqfGnYaVT
